/////////////////////////////////////////////////////////////////////////////
// Name:        userlogindialog.cpp
// Purpose:     
// Author:      
// Modified by: 
// Created:     16/10/2018 22:40:32
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 16/10/2018 22:40:32

// For compilers that support precompilation, includes "wx/wx.h".


////@begin includes
#include "wx/imaglist.h"
////@end includes

#include "userlogindialog.h"

////@begin XPM images
////@end XPM images


/*
 * UserLoginDialog type definition
 */

IMPLEMENT_DYNAMIC_CLASS(UserLoginDialog, wxDialog)


/*
 * UserLoginDialog event table definition
 */

	BEGIN_EVENT_TABLE(UserLoginDialog, wxDialog)

	////@begin UserLoginDialog event table entries
	////@end UserLoginDialog event table entries

	END_EVENT_TABLE()


	/*
	 * UserLoginDialog constructors
	 */

	UserLoginDialog::UserLoginDialog()
{
	Init();
}

UserLoginDialog::UserLoginDialog(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style)
{
	Init();
	Create(parent, id, caption, pos, size, style);
}


/*
 * UserLoginDialog creator
 */

bool UserLoginDialog::Create(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style)
{
	////@begin UserLoginDialog creation
	SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY | wxWS_EX_BLOCK_EVENTS);
	wxDialog::Create(parent, id, caption, pos, size, style);

	CreateControls();
	Centre();
	////@end UserLoginDialog creation
	return true;
}


/*
 * UserLoginDialog destructor
 */

UserLoginDialog::~UserLoginDialog()
{
	////@begin UserLoginDialog destruction
	////@end UserLoginDialog destruction
}


/*
 * Member initialisation
 */

void UserLoginDialog::Init()
{
	////@begin UserLoginDialog member initialisation
	////@end UserLoginDialog member initialisation
}


/*
 * Control creation for UserLoginDialog
 */

void UserLoginDialog::CreateControls()
{
	////@begin UserLoginDialog content construction
		// Generated by DialogBlocks, 16/10/2018 22:48:28 (unregistered)

	UserLoginDialog* itemDialog1 = this;

	wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
	itemDialog1->SetSizer(itemBoxSizer2);

	wxNotebook* itemNotebook1 = new wxNotebook(itemDialog1, ID_NOTEBOOK, wxDefaultPosition, wxDefaultSize, wxBK_DEFAULT);

	itemBoxSizer2->Add(itemNotebook1, 1, wxGROW | wxALL, 5);

	////@end UserLoginDialog content construction
}


/*
 * Should we show tooltips?
 */

bool UserLoginDialog::ShowToolTips()
{
	return true;
}

/*
 * Get bitmap resources
 */

wxBitmap UserLoginDialog::GetBitmapResource(const wxString& name)
{
	// Bitmap retrieval
////@begin UserLoginDialog bitmap retrieval
	wxUnusedVar(name);
	return wxNullBitmap;
	////@end UserLoginDialog bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon UserLoginDialog::GetIconResource(const wxString& name)
{
	// Icon retrieval
////@begin UserLoginDialog icon retrieval
	wxUnusedVar(name);
	return wxNullIcon;
	////@end UserLoginDialog icon retrieval
}
