/////////////////////////////////////////////////////////////////////////////
// Name:        userlogindialog.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     16/10/2018 22:40:32
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 16/10/2018 22:40:32

#ifndef _USERLOGINDIALOG_H_
#define _USERLOGINDIALOG_H_


/*!
 * Includes
 */

 ////@begin includes
#include "../common/common_wx.h"
#include "wx/notebook.h"
////@end includes

/*!
 * Forward declarations
 */

 ////@begin forward declarations
 ////@end forward declarations

 /*!
  * Control identifiers
  */

  ////@begin control identifiers
#define ID_USERLOGINDIALOG 10000
#define ID_NOTEBOOK 10001
#define SYMBOL_USERLOGINDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_USERLOGINDIALOG_TITLE _("UserLoginDialog")
#define SYMBOL_USERLOGINDIALOG_IDNAME ID_USERLOGINDIALOG
#define SYMBOL_USERLOGINDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_USERLOGINDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * UserLoginDialog class declaration
 */

class UserLoginDialog : public wxDialog
{
	DECLARE_DYNAMIC_CLASS(UserLoginDialog)
	DECLARE_EVENT_TABLE()

public:
	/// Constructors
	UserLoginDialog();
	UserLoginDialog(wxWindow* parent, wxWindowID id = SYMBOL_USERLOGINDIALOG_IDNAME, const wxString& caption = SYMBOL_USERLOGINDIALOG_TITLE, const wxPoint& pos = SYMBOL_USERLOGINDIALOG_POSITION, const wxSize& size = SYMBOL_USERLOGINDIALOG_SIZE, long style = SYMBOL_USERLOGINDIALOG_STYLE);

	/// Creation
	bool Create(wxWindow* parent, wxWindowID id = SYMBOL_USERLOGINDIALOG_IDNAME, const wxString& caption = SYMBOL_USERLOGINDIALOG_TITLE, const wxPoint& pos = SYMBOL_USERLOGINDIALOG_POSITION, const wxSize& size = SYMBOL_USERLOGINDIALOG_SIZE, long style = SYMBOL_USERLOGINDIALOG_STYLE);

	/// Destructor
	~UserLoginDialog();

	/// Initialises member variables
	void Init();

	/// Creates the controls and sizers
	void CreateControls();

	////@begin UserLoginDialog event handler declarations

	////@end UserLoginDialog event handler declarations

	////@begin UserLoginDialog member function declarations

		/// Retrieves bitmap resources
	wxBitmap GetBitmapResource(const wxString& name);

	/// Retrieves icon resources
	wxIcon GetIconResource(const wxString& name);
	////@end UserLoginDialog member function declarations

		/// Should we show tooltips?
	static bool ShowToolTips();

	////@begin UserLoginDialog member variables
	////@end UserLoginDialog member variables
};

#endif
// _USERLOGINDIALOG_H_
