//
// Created by zzzhr on 2018/9/11.
//

#ifndef QINGZHENYUN_LITE_SINGLE_URL_DOWNLOAD_TASK_H
#define QINGZHENYUN_LITE_SINGLE_URL_DOWNLOAD_TASK_H
#include <cpprest/http_client.h>


#endif //QINGZHENYUN_LITE_SINGLE_URL_DOWNLOAD_TASK_H
