/////////////////////////////////////////////////////////////////////////////
// Name:        add_offline_task.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     06/09/2018 00:11:30
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 06/09/2018 00:11:30

#ifndef _ADD_OFFLINE_TASK_H_
#define _ADD_OFFLINE_TASK_H_


/*!
 * Includes
 */

////@begin includes
#include "../../common/common_wx.h"
#include "wx/notebook.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers

#define SYMBOL_ADDOFFLINETASK_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_ADDOFFLINETASK_TITLE _("AddOfflineTask")
#define SYMBOL_ADDOFFLINETASK_IDNAME wxID_ANY
#define SYMBOL_ADDOFFLINETASK_SIZE wxSize(600, 400)
#define SYMBOL_ADDOFFLINETASK_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * AddOfflineTask class declaration
 */

class AddOfflineTask: public wxDialog
{
DECLARE_DYNAMIC_CLASS( AddOfflineTask )
DECLARE_EVENT_TABLE()

public:
    /// Constructors
    AddOfflineTask();
    AddOfflineTask( wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& caption = SYMBOL_ADDOFFLINETASK_TITLE, const wxPoint& pos = SYMBOL_ADDOFFLINETASK_POSITION, const wxSize& size = SYMBOL_ADDOFFLINETASK_SIZE, long style = SYMBOL_ADDOFFLINETASK_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& caption = SYMBOL_ADDOFFLINETASK_TITLE, const wxPoint& pos = SYMBOL_ADDOFFLINETASK_POSITION, const wxSize& size = SYMBOL_ADDOFFLINETASK_SIZE, long style = SYMBOL_ADDOFFLINETASK_STYLE );

    /// Destructor
    ~AddOfflineTask();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin AddOfflineTask event handler declarations

////@end AddOfflineTask event handler declarations

////@begin AddOfflineTask member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end AddOfflineTask member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

    bool IsTorrentPageSelected();

    wxString GetDownloadDir();

    wxString GetDownloadUrl();

    wxString GetTorrentFilePath();

    void DoOpenFiles(const wxArrayString &fileNames);

    void OnFileOpen(wxCommandEvent& event );

////@begin AddOfflineTask member variables
private:
    void OnChangeBtnClicked(wxCommandEvent &event);
    wxTextCtrl* downloadDirTextCtrl = nullptr;
    wxNotebook* mainNotebook = nullptr;
    wxTextCtrl* downloadUrlInput = nullptr;
    wxTextCtrl* filePathTextCtrl = nullptr;
////@end AddOfflineTask member variables

};

#endif
// _ADD_OFFLINE_TASK_H_
