/////////////////////////////////////////////////////////////////////////////
// Name:        task_detail.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     08/09/2018 13:55:19
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 08/09/2018 13:55:19

#ifndef _TASK_DETAIL_H_
#define _TASK_DETAIL_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif
#include "wx/statline.h"
#include "cpprest/http_client.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers

#define SYMBOL_TASKDETAIL_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_TASKDETAIL_TITLE _("TaskDetail")
#define SYMBOL_TASKDETAIL_IDNAME wxID_ANY
#define SYMBOL_TASKDETAIL_SIZE wxSize(400, 300)
#define SYMBOL_TASKDETAIL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * TaskDetail class declaration
 */

class TaskDetail: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( TaskDetail )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    TaskDetail();
    TaskDetail( wxWindow* parent, wxWindowID id = SYMBOL_TASKDETAIL_IDNAME, const wxString& caption = SYMBOL_TASKDETAIL_TITLE, const wxPoint& pos = SYMBOL_TASKDETAIL_POSITION, const wxSize& size = SYMBOL_TASKDETAIL_SIZE, long style = SYMBOL_TASKDETAIL_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_TASKDETAIL_IDNAME, const wxString& caption = SYMBOL_TASKDETAIL_TITLE, const wxPoint& pos = SYMBOL_TASKDETAIL_POSITION, const wxSize& size = SYMBOL_TASKDETAIL_SIZE, long style = SYMBOL_TASKDETAIL_STYLE );

    /// Destructor
    ~TaskDetail();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin TaskDetail event handler declarations

////@end TaskDetail event handler declarations

////@begin TaskDetail member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end TaskDetail member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

	void setView(const web::json::value& v);

////@begin TaskDetail member variables
private:
	wxTextCtrl* taskNameTextCtrl = nullptr;
	wxTextCtrl* taskIdTextCtrl = nullptr;
	wxStaticText* taskStatusStaticText = nullptr;
	wxStaticText* progressStaticText = nullptr;
	wxTextCtrl* pathStaticText = nullptr;
	wxStaticText* mimeStaticText = nullptr;
	//wxStaticText* previewStaticText = nullptr;
////@end TaskDetail member variables
};

#endif
    // _TASK_DETAIL_H_
