/////////////////////////////////////////////////////////////////////////////
// Name:        videopreviewframe.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     07/09/2018 14:48:49
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 07/09/2018 14:48:49

#ifndef _VIDEOPREVIEWFRAME_H_
#define _VIDEOPREVIEWFRAME_H_


/*!
 * Includes
 */

 ////@begin includes
#include "wx/mediactrl.h"
#include "wx/cshelp.h"
#include "cpprest/json.h"
#include <vlc/vlc.h>
#include <climits>

////@end includes

/*!
 * Forward declarations
 */

 ////@begin forward declarations
 ////@end forward declarations

 /*!
  * Control identifiers
  */

  ////@begin control identifiers

#define SYMBOL_VIDEOPREVIEWFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_VIDEOPREVIEWFRAME_TITLE _("VideoPreviewFrame")
#define SYMBOL_VIDEOPREVIEWFRAME_IDNAME ID_VIDEOPREVIEWFRAME
#define SYMBOL_VIDEOPREVIEWFRAME_SIZE wxSize(640, 500)
#define SYMBOL_VIDEOPREVIEWFRAME_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * VideoPreviewFrame class declaration
 */

class VideoPreviewFrame : public wxDialog
{
	DECLARE_DYNAMIC_CLASS(VideoPreviewFrame)
	DECLARE_EVENT_TABLE()

public:
	/// Constructors
	VideoPreviewFrame();
	VideoPreviewFrame(const utility::string_t &path,wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& caption = SYMBOL_VIDEOPREVIEWFRAME_TITLE, const wxPoint& pos = SYMBOL_VIDEOPREVIEWFRAME_POSITION, const wxSize& size = SYMBOL_VIDEOPREVIEWFRAME_SIZE, long style = SYMBOL_VIDEOPREVIEWFRAME_STYLE);

	/// Creation
	bool Create(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& caption = SYMBOL_VIDEOPREVIEWFRAME_TITLE, const wxPoint& pos = SYMBOL_VIDEOPREVIEWFRAME_POSITION, const wxSize& size = SYMBOL_VIDEOPREVIEWFRAME_SIZE, long style = SYMBOL_VIDEOPREVIEWFRAME_STYLE);

	/// Destructor
	~VideoPreviewFrame();

	/// Initialises member variables
	void Init();

	/// Creates the controls and sizers
	void CreateControls();

	////@begin VideoPreviewFrame event handler declarations

		/// wxEVT_CLOSE_WINDOW event handler for ID_VIDEOPREVIEWFRAME
	void OnCloseWindow(wxCloseEvent& event);


	////@end VideoPreviewFrame event handler declarations

	////@begin VideoPreviewFrame member function declarations

		/// Retrieves bitmap resources
	wxBitmap GetBitmapResource(const wxString& name);

	/// Retrieves icon resources
	wxIcon GetIconResource(const wxString& name);
	////@end VideoPreviewFrame member function declarations

		/// Should we show tooltips?
	static bool ShowToolTips();

	////@begin VideoPreviewFrame member variables
private:
	wxWindow * playerWidget;
	void OnThreadEvent(wxThreadEvent & event);
	void PlayPreview(const web::json::array & array);
	libvlc_media_player_t *media_player = nullptr;
	libvlc_instance_t *vlc_inst = nullptr;
	libvlc_event_manager_t *vlc_evt_man = nullptr;
	////@end VideoPreviewFrame member variables
};

#endif
// _VIDEOPREVIEWFRAME_H_
