/////////////////////////////////////////////////////////////////////////////
// Name:        videopreviewframe.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     07/09/2018 14:48:49
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 07/09/2018 14:48:49

#ifndef _VIDEOPREVIEWFRAME_H_
#define _VIDEOPREVIEWFRAME_H_


/*!
 * Includes
 */

 ////@begin includes
#include "../../common/common_wx.h"
#include "cpprest/json.h"
#include <climits>
#include <mpv/client.h>
#include "../../util/simple_timer.h"
#include "../../common/common_event_ids.h"
////@end includes

/*!
 * Forward declarations
 */

 ////@begin forward declarations
 ////@end forward declarations

 /*!
  * Control identifiers
  */

  ////@begin control identifiers

#define SYMBOL_VIDEOPREVIEWFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_VIDEOPREVIEWFRAME_TITLE _("VideoPreviewFrame")
#define SYMBOL_VIDEOPREVIEWFRAME_IDNAME ID_VIDEOPREVIEWFRAME
#define SYMBOL_VIDEOPREVIEWFRAME_SIZE wxSize(640, 500)
#define SYMBOL_VIDEOPREVIEWFRAME_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * VideoPreviewFrame class declaration
 */

class VideoPreviewFrame : public wxDialog
{
	DECLARE_DYNAMIC_CLASS(VideoPreviewFrame)
	DECLARE_EVENT_TABLE()
	/*
    static void wakeup(void *ctx)
    {
        // This callback is invoked from any mpv thread (but possibly also
        // recursively from a thread that is calling the mpv API). Just notify
        // the Qt GUI thread to wake up (so that it can process events with
        // mpv_wait_event()), and return as quickly as possible.


        VideoPreviewFrame *mainwindow = (VideoPreviewFrame *)ctx;
        //mainwindow->CheckTimer();
        wxThreadEvent event(wxEVT_THREAD);
        //auto ts = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
        //event.SetTimestamp(ts);
        //event.SetId(this->GetId());
        event.SetInt(VIDEO_PLAYER_WAKEUP);
        //event.SetPayload(v);
        //std::cout << "Tick0" << std::endl;
        wxQueueEvent(mainwindow, event.Clone());

        //emit mainwindow->mpv_events();
    }
    */
public:
	/// Constructors
	VideoPreviewFrame();
	VideoPreviewFrame(const utility::string_t &path,wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& caption = SYMBOL_VIDEOPREVIEWFRAME_TITLE, const wxPoint& pos = SYMBOL_VIDEOPREVIEWFRAME_POSITION, const wxSize& size = SYMBOL_VIDEOPREVIEWFRAME_SIZE, long style = SYMBOL_VIDEOPREVIEWFRAME_STYLE);

	/// Creation
	bool Create(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& caption = SYMBOL_VIDEOPREVIEWFRAME_TITLE, const wxPoint& pos = SYMBOL_VIDEOPREVIEWFRAME_POSITION, const wxSize& size = SYMBOL_VIDEOPREVIEWFRAME_SIZE, long style = SYMBOL_VIDEOPREVIEWFRAME_STYLE);

	/// Destructor
	~VideoPreviewFrame();

	/// Initialises member variables
	void Init();

	/// Creates the controls and sizers
	void CreateControls();

	////@begin VideoPreviewFrame event handler declarations

		/// wxEVT_CLOSE_WINDOW event handler for ID_VIDEOPREVIEWFRAME
	void OnCloseWindow(wxCloseEvent& event);

    void CheckTimer();

	////@end VideoPreviewFrame event handler declarations

	////@begin VideoPreviewFrame member function declarations

		/// Retrieves bitmap resources
	wxBitmap GetBitmapResource(const wxString& name);

	/// Retrieves icon resources
	wxIcon GetIconResource(const wxString& name);
	////@end VideoPreviewFrame member function declarations

		/// Should we show tooltips?
	static bool ShowToolTips();
    void CloseInner();

	////@begin VideoPreviewFrame member variables
private:
	void OnThreadEvent(wxThreadEvent & event);
	wxTextCtrl* logTextCtrl = nullptr;
	void printLog(utility::string_t log);
	void PlayPreview(const web::json::array & array);
	mpv_handle* ctx = nullptr;

	bool emitEvent = true;

	//SimpleTimer time = SimpleTimer();
	//bool continuePlay = true;

};

#endif
// _VIDEOPREVIEWFRAME_H_
