/////////////////////////////////////////////////////////////////////////////
// Name:        add_directory_dialog.cpp
// Purpose:     
// Author:      
// Modified by: 
// Created:     05/09/2018 20:13:34
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 05/09/2018 20:13:34

// For compilers that support precompilation, includes "wx/wx.h".

////@begin includes
////@end includes

#include "add_directory_dialog.h"

////@begin XPM images

////@end XPM images


/*
 * AddDirectoryDialog type definition
 */

IMPLEMENT_DYNAMIC_CLASS(AddDirectoryDialog, wxDialog)


/*
 * AddDirectoryDialog event table definition
 */

	BEGIN_EVENT_TABLE(AddDirectoryDialog, wxDialog)

	////@begin AddDirectoryDialog event table entries
	////@end AddDirectoryDialog event table entries

	END_EVENT_TABLE()


	/*
	 * AddDirectoryDialog constructors
	 */

	AddDirectoryDialog::AddDirectoryDialog()
{
	Init();
}

AddDirectoryDialog::AddDirectoryDialog(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style)
{
	Init();
	Create(parent, id, caption, pos, size, style);
}


/*
 * AddDirectoryDialog creator
 */

bool AddDirectoryDialog::Create(wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style)
{
	////@begin AddDirectoryDialog creation
	SetExtraStyle(wxWS_EX_VALIDATE_RECURSIVELY | wxWS_EX_BLOCK_EVENTS);
	wxDialog::Create(parent, id, caption, pos, size, style);

	CreateControls();
	Centre();
	////@end AddDirectoryDialog creation
	return true;
}


/*
 * AddDirectoryDialog destructor
 */

AddDirectoryDialog::~AddDirectoryDialog()
{
	////@begin AddDirectoryDialog destruction
	////@end AddDirectoryDialog destruction
}


/*
 * Member initialisation
 */

void AddDirectoryDialog::Init()
{
	////@begin AddDirectoryDialog member initialisation
	////@end AddDirectoryDialog member initialisation
}


/*
 * Control creation for AddDirectoryDialog
 */

void AddDirectoryDialog::CreateControls()
{
	////@begin AddDirectoryDialog content construction
		// Generated by DialogBlocks, 05/09/2018 20:13:34 (unregistered)

	AddDirectoryDialog* itemDialog1 = this;

	wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
	itemDialog1->SetSizer(itemBoxSizer2);

	wxBoxSizer* itemBoxSizer1 = new wxBoxSizer(wxVERTICAL);
	itemBoxSizer2->Add(itemBoxSizer1, 1, wxGROW, 5);

	wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxHORIZONTAL);
	itemBoxSizer1->Add(itemBoxSizer3, 1, wxGROW | wxALL, 5);

	wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
	itemBoxSizer3->Add(itemBoxSizer4, 1, wxALIGN_CENTER_VERTICAL | wxALL, 5);

	wxStaticText* itemStaticText5 = new wxStaticText(itemDialog1, wxID_STATIC, _("New Directory Name"), wxDefaultPosition, wxDefaultSize, 0);
	itemBoxSizer4->Add(itemStaticText5, 0, wxALIGN_CENTER_VERTICAL | wxALL, 5);

	directoryNameInput = new wxTextCtrl(itemDialog1, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0);
	directoryNameInput->SetMaxLength(128);
	itemBoxSizer4->Add(directoryNameInput, 1, wxALIGN_CENTER_VERTICAL | wxALL, 5);

	wxStdDialogButtonSizer* itemStdDialogButtonSizer7 = new wxStdDialogButtonSizer;

	itemBoxSizer1->Add(itemStdDialogButtonSizer7, 0, wxALIGN_RIGHT | wxALL, 5);
	wxButton* itemButton8 = new wxButton(itemDialog1, wxID_OK, _("&OK"), wxDefaultPosition, wxDefaultSize, 0);
	itemStdDialogButtonSizer7->AddButton(itemButton8);

	wxButton* itemButton9 = new wxButton(itemDialog1, wxID_CANCEL, _("&Cancel"), wxDefaultPosition, wxDefaultSize, 0);
	itemStdDialogButtonSizer7->AddButton(itemButton9);

	itemStdDialogButtonSizer7->Realize();

	////@end AddDirectoryDialog content construction
}


/*
 * Should we show tooltips?
 */

bool AddDirectoryDialog::ShowToolTips()
{
	return true;
}

/*
 * Get bitmap resources
 */

wxBitmap AddDirectoryDialog::GetBitmapResource(const wxString& name)
{
	// Bitmap retrieval
////@begin AddDirectoryDialog bitmap retrieval
	wxUnusedVar(name);
	return wxNullBitmap;
	////@end AddDirectoryDialog bitmap retrieval
}

/*
 * Get icon resources
 */

wxIcon AddDirectoryDialog::GetIconResource(const wxString& name)
{
	// Icon retrieval
////@begin AddDirectoryDialog icon retrieval
	wxUnusedVar(name);
	return wxNullIcon;
	////@end AddDirectoryDialog icon retrieval
}


wxString AddDirectoryDialog::GetUserInput() {
	return directoryNameInput->GetValue();
}