/////////////////////////////////////////////////////////////////////////////
// Name:        add_directory_dialog.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     05/09/2018 20:13:34
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 05/09/2018 20:13:34

#ifndef _ADD_DIRECTORY_DIALOG_H_
#define _ADD_DIRECTORY_DIALOG_H_


/*!
 * Includes
 */

#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

 ////@begin includes
 ////@end includes
 /*!
  * Forward declarations
  */

  ////@begin forward declarations
  ////@end forward declarations

  /*!
   * Control identifiers
   */

   ////@begin control identifiers
#define ID_ADDDIRECTORYDIALOG 10000
#define SYMBOL_ADDDIRECTORYDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_ADDDIRECTORYDIALOG_TITLE _("AddDirectoryDialog")
#define SYMBOL_ADDDIRECTORYDIALOG_IDNAME ID_ADDDIRECTORYDIALOG
#define SYMBOL_ADDDIRECTORYDIALOG_SIZE wxSize(400, -1)
#define SYMBOL_ADDDIRECTORYDIALOG_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * AddDirectoryDialog class declaration
 */

class AddDirectoryDialog : public wxDialog
{
	DECLARE_DYNAMIC_CLASS(AddDirectoryDialog)
	DECLARE_EVENT_TABLE()

public:
	/// Constructors
	AddDirectoryDialog();
	AddDirectoryDialog(wxWindow* parent, wxWindowID id = SYMBOL_ADDDIRECTORYDIALOG_IDNAME, const wxString& caption = SYMBOL_ADDDIRECTORYDIALOG_TITLE, const wxPoint& pos = SYMBOL_ADDDIRECTORYDIALOG_POSITION, const wxSize& size = SYMBOL_ADDDIRECTORYDIALOG_SIZE, long style = SYMBOL_ADDDIRECTORYDIALOG_STYLE);

	/// Creation
	bool Create(wxWindow* parent, wxWindowID id = SYMBOL_ADDDIRECTORYDIALOG_IDNAME, const wxString& caption = SYMBOL_ADDDIRECTORYDIALOG_TITLE, const wxPoint& pos = SYMBOL_ADDDIRECTORYDIALOG_POSITION, const wxSize& size = SYMBOL_ADDDIRECTORYDIALOG_SIZE, long style = SYMBOL_ADDDIRECTORYDIALOG_STYLE);

	/// Destructor
	~AddDirectoryDialog();

	/// Initialises member variables
	void Init();

	/// Creates the controls and sizers
	void CreateControls();

	////@begin AddDirectoryDialog event handler declarations
	////@end AddDirectoryDialog event handler declarations

	////@begin AddDirectoryDialog member function declarations
		/// Retrieves bitmap resources
	wxBitmap GetBitmapResource(const wxString& name);

	/// Retrieves icon resources
	wxIcon GetIconResource(const wxString& name);
	////@end AddDirectoryDialog member function declarations

		/// Should we show tooltips?
	static bool ShowToolTips();

	wxString getUserInput();
private:
	wxTextCtrl* directoryNameInput = nullptr;

	////@begin AddDirectoryDialog member variables
	////@end AddDirectoryDialog member variables
};

#endif
// _ADD_DIRECTORY_DIALOG_H_
