/////////////////////////////////////////////////////////////////////////////
// Name:        filedetail.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     21/09/2018 23:30:50
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 21/09/2018 23:30:50

#ifndef _FILEDETAIL_H_
#define _FILEDETAIL_H_


/*!
 * Includes
 */

 // For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

 ////@begin includes
#include "wx/statline.h"
#include <cpprest/json.h>
////@end includes

/*!
 * Forward declarations
 */

 ////@begin forward declarations
 ////@end forward declarations

 /*!
  * Control identifiers
  */

  ////@begin control identifiers

#define SYMBOL_FILEDETAIL_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxTAB_TRAVERSAL
#define SYMBOL_FILEDETAIL_TITLE _("FileDetail")
#define SYMBOL_FILEDETAIL_IDNAME ID_FILEDETAIL
#define SYMBOL_FILEDETAIL_SIZE wxSize(400, 300)
#define SYMBOL_FILEDETAIL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * FileDetail class declaration
 */

class FileDetail : public wxDialog
{
	DECLARE_DYNAMIC_CLASS(FileDetail)
	DECLARE_EVENT_TABLE()

public:
	/// Constructors
	FileDetail();
	FileDetail(wxWindow* parent, const web::json::value &info, wxWindowID id = wxID_ANY, const wxString& caption = SYMBOL_FILEDETAIL_TITLE, const wxPoint& pos = SYMBOL_FILEDETAIL_POSITION, const wxSize& size = SYMBOL_FILEDETAIL_SIZE, long style = SYMBOL_FILEDETAIL_STYLE);

	/// Creation
	bool Create(wxWindow* parent, const web::json::value &info, wxWindowID id = wxID_ANY, const wxString& caption = SYMBOL_FILEDETAIL_TITLE, const wxPoint& pos = SYMBOL_FILEDETAIL_POSITION, const wxSize& size = SYMBOL_FILEDETAIL_SIZE, long style = SYMBOL_FILEDETAIL_STYLE);

	/// Destructor
	~FileDetail();

	/// Initialises member variables
	void Init();

	/// Creates the controls and sizers
	void CreateControls(const web::json::value &info);

	////@begin FileDetail event handler declarations

	////@end FileDetail event handler declarations

	////@begin FileDetail member function declarations

		/// Retrieves bitmap resources
	wxBitmap GetBitmapResource(const wxString& name);

	/// Retrieves icon resources
	wxIcon GetIconResource(const wxString& name);
	////@end FileDetail member function declarations

		/// Should we show tooltips?
	static bool ShowToolTips();
private:
	void CloseBtnClicked(wxCommandEvent &event);
	
	////@begin FileDetail member variables
	////@end FileDetail member variables
};

#endif
// _FILEDETAIL_H_
